databases:
  - name: transaction_truck
    databaseName: transaction_truck
    user: transaction_truck_user

services:
  - type: web
    name: transaction_truck
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: transaction_truck
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false